issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters:
  enable-all: true
  disable:
    - wrapcheck
    - varnamelen
    - exhaustruct
    - exportloopref

linters-settings:
  depguard:
    rules:
      prevent_accidental_imports:
        allow:
          - $gostd
          - github.com/grafana/xk6
          - github.com/spf13/cobra
          - github.com/spf13/pflag
          - github.com/cli/go-gh/v2
          - github.com/google/go-github/v62
