project_name: xk6
version: 2

before:
  hooks:
    - go mod tidy
    - go run ./tools/gendoc README.md

builds:
  - id: xk6
    main: ./cmd/xk6
    binary: xk6
    goos: ["linux", "windows"]
    goarch: ["amd64", "arm64"]
    ldflags: "-s -w -X github.com/grafana/xk6/internal/cli.version={{.Version}}"
    env: ["CGO_ENABLED=0"]
  - id: gh-xk6
    main: ./cmd/gh-xk6
    binary: gh-xk6
    goos: ["linux", "windows"]
    goarch: ["amd64", "arm64"]
    ldflags: "-s -w -X github.com/grafana/xk6/internal/cli.version={{.Version}}"
    env: ["CGO_ENABLED=0"]

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

archives:
  - id: binary
    builds: ["gh-xk6"]
    formats: ["binary"]
    name_template: "gh-xk6_{{ .Tag }}_{{ .Os }}-{{ .Arch }}{{if .Arm}}_{{.Arm}}{{end}}"
  - id: bundle
    builds: ["xk6"]
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next+{{.ShortCommit}}{{if .IsGitDirty}}.dirty{{else}}{{end}}"

changelog:
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^build:"
