name: prebuild
on:
  workflow_dispatch:
  push:
    paths:
      - ".devcontainers/**"

jobs:
  lint:
    name: prebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/grafana/gh-xk6-devcontainer
          cacheFrom: ghcr.io/grafana/gh-xk6-devcontainer
          push: always
