name: prebuild
on:
  workflow_dispatch:
  push:
    paths:
      - ".devcontainers/**"

jobs:
  prebuild:
    name: prebuild
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/grafana/gh-xk6-devcontainer
          cacheFrom: ghcr.io/grafana/gh-xk6-devcontainer
          push: always
