name: Publish TechDocs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - '.github/workflows/publish-techdocs.yaml'
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
permissions: {}
jobs:
  publish-docs:
    uses: grafana/shared-workflows/.github/workflows/publish-techdocs.yaml@b2f47cf9a22221fcb6fb816ffea2fd382971b218 # main
    permissions:
      contents: read
      id-token: write
    with:
      namespace: default
      kind: component
      name: gh-xk6
      default-working-directory: .
