name: Publish TechDocs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - '.github/workflows/publish-techdocs.yaml'
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
permissions: {}
jobs:
  publish-docs:
    uses: grafana/shared-workflows/.github/workflows/publish-techdocs.yaml@e942a3a5775e102da33db1bcb193cfddb3a47a26 # main
    permissions:
      contents: read
      id-token: write
    with:
      namespace: default
      kind: component
      name: gh-xk6
      default-working-directory: .
